/**
 * Board-standard curriculum data — official chapters, subjects per grade, and terminology.
 * Used to inject accurate context into AI prompts so generated curricula match real syllabi.
 */

// ─── GRADE → SUBJECTS mapping per board ────────────────────────────────────────

export const BOARD_GRADE_SUBJECTS: Record<string, Record<string, string[]>> = {
  CBSE: {
    'Grade 1':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies (EVS)'],
    'Grade 2':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies (EVS)'],
    'Grade 3':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies (EVS)'],
    'Grade 4':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies (EVS)'],
    'Grade 5':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies (EVS)'],
    'Grade 6':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Science', 'Sanskrit/Computer'],
    'Grade 7':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Science', 'Sanskrit/Computer'],
    'Grade 8':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Science', 'Sanskrit/Computer'],
    'Grade 9':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Science', 'Information Technology'],
    'Grade 10': ['Mathematics', 'English', 'Hindi', 'Science', 'Social Science', 'Information Technology'],
    'Grade 11': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science', 'Accountancy', 'Business Studies', 'Economics', 'History', 'Political Science', 'Geography'],
    'Grade 12': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science', 'Accountancy', 'Business Studies', 'Economics', 'History', 'Political Science', 'Geography'],
  },
  ICSE: {
    'Grade 1':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies'],
    'Grade 2':  ['Mathematics', 'English', 'Hindi', 'Environmental Studies'],
    'Grade 3':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Studies'],
    'Grade 4':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Studies'],
    'Grade 5':  ['Mathematics', 'English', 'Hindi', 'Science', 'Social Studies'],
    'Grade 6':  ['Mathematics', 'English', 'Hindi', 'Physics', 'Chemistry', 'Biology', 'History & Civics', 'Geography', 'Computer Applications'],
    'Grade 7':  ['Mathematics', 'English', 'Hindi', 'Physics', 'Chemistry', 'Biology', 'History & Civics', 'Geography', 'Computer Applications'],
    'Grade 8':  ['Mathematics', 'English', 'Hindi', 'Physics', 'Chemistry', 'Biology', 'History & Civics', 'Geography', 'Computer Applications'],
    'Grade 9':  ['Mathematics', 'English', 'Hindi', 'Physics', 'Chemistry', 'Biology', 'History & Civics', 'Geography', 'Computer Applications', 'Economics'],
    'Grade 10': ['Mathematics', 'English', 'Hindi', 'Physics', 'Chemistry', 'Biology', 'History & Civics', 'Geography', 'Computer Applications', 'Economics'],
    'Grade 11': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science', 'Commerce', 'Economics', 'History', 'Political Science'],
    'Grade 12': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science', 'Commerce', 'Economics', 'History', 'Political Science'],
  },
  IB: {
    'Grade 1':  ['Mathematics', 'Language Arts', 'Individuals and Societies', 'Science', 'Arts', 'Physical Education'],
    'Grade 2':  ['Mathematics', 'Language Arts', 'Individuals and Societies', 'Science', 'Arts', 'Physical Education'],
    'Grade 3':  ['Mathematics', 'Language Arts', 'Individuals and Societies', 'Science', 'Arts', 'Physical Education'],
    'Grade 4':  ['Mathematics', 'Language Arts', 'Individuals and Societies', 'Science', 'Arts', 'Physical Education'],
    'Grade 5':  ['Mathematics', 'Language Arts', 'Individuals and Societies', 'Science', 'Arts', 'Physical Education'],
    'Grade 6':  ['Mathematics', 'Language and Literature', 'Individuals and Societies', 'Sciences', 'Arts', 'Physical and Health Education', 'Design'],
    'Grade 7':  ['Mathematics', 'Language and Literature', 'Individuals and Societies', 'Sciences', 'Arts', 'Physical and Health Education', 'Design'],
    'Grade 8':  ['Mathematics', 'Language and Literature', 'Individuals and Societies', 'Sciences', 'Arts', 'Physical and Health Education', 'Design'],
    'Grade 9':  ['Mathematics', 'Language and Literature', 'Individuals and Societies', 'Sciences', 'Arts', 'Physical and Health Education', 'Design'],
    'Grade 10': ['Mathematics', 'Language and Literature', 'Individuals and Societies', 'Sciences', 'Arts', 'Physical and Health Education', 'Design'],
    'Grade 11': ['Mathematics: Analysis and Approaches', 'Physics', 'Chemistry', 'Biology', 'Language and Literature', 'History', 'Economics', 'Computer Science', 'Visual Arts', 'Theory of Knowledge'],
    'Grade 12': ['Mathematics: Analysis and Approaches', 'Physics', 'Chemistry', 'Biology', 'Language and Literature', 'History', 'Economics', 'Computer Science', 'Visual Arts', 'Extended Essay'],
  },
  Cambridge: {
    'Grade 1':  ['Mathematics', 'English', 'Science'],
    'Grade 2':  ['Mathematics', 'English', 'Science'],
    'Grade 3':  ['Mathematics', 'English', 'Science', 'Social Studies'],
    'Grade 4':  ['Mathematics', 'English', 'Science', 'Social Studies'],
    'Grade 5':  ['Mathematics', 'English', 'Science', 'Social Studies'],
    'Grade 6':  ['Mathematics', 'English as a Second Language', 'Science', 'History', 'Geography', 'ICT'],
    'Grade 7':  ['Mathematics', 'English as a Second Language', 'Science', 'History', 'Geography', 'ICT'],
    'Grade 8':  ['Mathematics', 'English as a Second Language', 'Science', 'History', 'Geography', 'ICT'],
    'Grade 9':  ['Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Computer Science', 'Economics'],
    'Grade 10': ['Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Computer Science', 'Economics'],
    'Grade 11': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English Language', 'Computer Science', 'Economics', 'History', 'Geography'],
    'Grade 12': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English Language', 'Computer Science', 'Economics', 'History', 'Geography'],
  },
};

// ─── CBSE OFFICIAL NCERT CHAPTERS per Grade per Subject ─────────────────────────

export const CBSE_CHAPTERS: Record<string, Record<string, string[]>> = {

  // ── MATHEMATICS ──────────────────────────────────────────────────────────────
  Mathematics: {
    'Grade 1': [
      'Chapter 1: Shapes and Space',
      'Chapter 2: Numbers from One to Nine',
      'Chapter 3: Addition',
      'Chapter 4: Subtraction',
      'Chapter 5: Numbers from Ten to Twenty',
      'Chapter 6: Time',
      'Chapter 7: Measurement',
      'Chapter 8: Numbers from Twenty-one to Fifty',
      'Chapter 9: Data Handling',
      'Chapter 10: Patterns',
      'Chapter 11: Numbers',
      'Chapter 12: Money',
      'Chapter 13: How Many',
    ],
    'Grade 2': [
      'Chapter 1: What is Long, What is Round?',
      'Chapter 2: Counting in Groups',
      'Chapter 3: How Much Can You Carry?',
      'Chapter 4: Counting in Tens',
      'Chapter 5: Patterns',
      'Chapter 6: Footprints',
      'Chapter 7: Jugs and Mugs',
      'Chapter 8: Tens and Ones',
      'Chapter 9: My Funday',
      'Chapter 10: Add our Points',
      'Chapter 11: Lines and Lines',
      'Chapter 12: Give and Take',
      'Chapter 13: The Longest Step',
      'Chapter 14: Birds Come, Birds Go',
      'Chapter 15: How Many Ponytails?',
    ],
    'Grade 3': [
      'Chapter 1: Where to Look From',
      'Chapter 2: Fun with Numbers',
      'Chapter 3: Give and Take',
      'Chapter 4: Long and Short',
      'Chapter 5: Shapes and Designs',
      'Chapter 6: Fun with Give and Take',
      'Chapter 7: Time Goes On',
      'Chapter 8: Who is Heavier?',
      'Chapter 9: How Many Times?',
      'Chapter 10: Play with Patterns',
      'Chapter 11: Jugs and Mugs',
      'Chapter 12: Can We Share?',
      'Chapter 13: Smart Charts',
      'Chapter 14: Rupees and Paise',
    ],
    'Grade 4': [
      'Chapter 1: Building with Bricks',
      'Chapter 2: Long and Short',
      'Chapter 3: A Trip to Bhopal',
      'Chapter 4: Tick-Tick-Tick',
      'Chapter 5: The Way The World Looks',
      'Chapter 6: The Junk Seller',
      'Chapter 7: Jugs and Mugs',
      'Chapter 8: Carts and Wheels',
      'Chapter 9: Halves and Quarters',
      'Chapter 10: Play with Patterns',
      'Chapter 11: Tables and Shares',
      'Chapter 12: How Heavy? How Light?',
      'Chapter 13: Fields and Fences',
      'Chapter 14: Smart Charts',
    ],
    'Grade 5': [
      'Chapter 1: The Fish Tale',
      'Chapter 2: Shapes and Angles',
      'Chapter 3: How Many Squares?',
      'Chapter 4: Parts and Wholes',
      'Chapter 5: Does it Look the Same?',
      'Chapter 6: Be My Multiple, I\'ll be Your Factor',
      'Chapter 7: Can You See the Pattern?',
      'Chapter 8: Mapping Your Way',
      'Chapter 9: Boxes and Sketches',
      'Chapter 10: Tenths and Hundredths',
      'Chapter 11: Area and its Boundary',
      'Chapter 12: Smart Charts',
      'Chapter 13: Ways to Multiply and Divide',
      'Chapter 14: How Big? How Heavy?',
    ],
    'Grade 6': [
      'Chapter 1: Knowing Our Numbers',
      'Chapter 2: Whole Numbers',
      'Chapter 3: Playing with Numbers',
      'Chapter 4: Basic Geometrical Ideas',
      'Chapter 5: Understanding Elementary Shapes',
      'Chapter 6: Integers',
      'Chapter 7: Fractions',
      'Chapter 8: Decimals',
      'Chapter 9: Data Handling',
      'Chapter 10: Mensuration',
      'Chapter 11: Algebra',
      'Chapter 12: Ratio and Proportion',
      'Chapter 13: Symmetry',
      'Chapter 14: Practical Geometry',
    ],
    'Grade 7': [
      'Chapter 1: Integers',
      'Chapter 2: Fractions and Decimals',
      'Chapter 3: Data Handling',
      'Chapter 4: Simple Equations',
      'Chapter 5: Lines and Angles',
      'Chapter 6: The Triangle and its Properties',
      'Chapter 7: Congruence of Triangles',
      'Chapter 8: Comparing Quantities',
      'Chapter 9: Rational Numbers',
      'Chapter 10: Practical Geometry',
      'Chapter 11: Perimeter and Area',
      'Chapter 12: Algebraic Expressions',
      'Chapter 13: Exponents and Powers',
      'Chapter 14: Symmetry',
      'Chapter 15: Visualising Solid Shapes',
    ],
    'Grade 8': [
      'Chapter 1: Rational Numbers',
      'Chapter 2: Linear Equations in One Variable',
      'Chapter 3: Understanding Quadrilaterals',
      'Chapter 4: Practical Geometry',
      'Chapter 5: Data Handling',
      'Chapter 6: Squares and Square Roots',
      'Chapter 7: Cubes and Cube Roots',
      'Chapter 8: Comparing Quantities',
      'Chapter 9: Algebraic Expressions and Identities',
      'Chapter 10: Visualising Solid Shapes',
      'Chapter 11: Mensuration',
      'Chapter 12: Exponents and Powers',
      'Chapter 13: Direct and Inverse Proportions',
      'Chapter 14: Factorisation',
      'Chapter 15: Introduction to Graphs',
      'Chapter 16: Playing with Numbers',
    ],
    'Grade 9': [
      'Chapter 1: Number Systems',
      'Chapter 2: Polynomials',
      'Chapter 3: Coordinate Geometry',
      'Chapter 4: Linear Equations in Two Variables',
      'Chapter 5: Introduction to Euclid\'s Geometry',
      'Chapter 6: Lines and Angles',
      'Chapter 7: Triangles',
      'Chapter 8: Quadrilaterals',
      'Chapter 9: Areas of Parallelograms and Triangles',
      'Chapter 10: Circles',
      'Chapter 11: Constructions',
      'Chapter 12: Heron\'s Formula',
      'Chapter 13: Surface Areas and Volumes',
      'Chapter 14: Statistics',
      'Chapter 15: Probability',
    ],
    'Grade 10': [
      'Chapter 1: Real Numbers',
      'Chapter 2: Polynomials',
      'Chapter 3: Pair of Linear Equations in Two Variables',
      'Chapter 4: Quadratic Equations',
      'Chapter 5: Arithmetic Progressions',
      'Chapter 6: Triangles',
      'Chapter 7: Coordinate Geometry',
      'Chapter 8: Introduction to Trigonometry',
      'Chapter 9: Some Applications of Trigonometry',
      'Chapter 10: Circles',
      'Chapter 11: Constructions',
      'Chapter 12: Areas Related to Circles',
      'Chapter 13: Surface Areas and Volumes',
      'Chapter 14: Statistics',
      'Chapter 15: Probability',
    ],
    'Grade 11': [
      'Chapter 1: Sets',
      'Chapter 2: Relations and Functions',
      'Chapter 3: Trigonometric Functions',
      'Chapter 4: Principle of Mathematical Induction',
      'Chapter 5: Complex Numbers and Quadratic Equations',
      'Chapter 6: Linear Inequalities',
      'Chapter 7: Permutations and Combinations',
      'Chapter 8: Binomial Theorem',
      'Chapter 9: Sequences and Series',
      'Chapter 10: Straight Lines',
      'Chapter 11: Conic Sections',
      'Chapter 12: Introduction to Three Dimensional Geometry',
      'Chapter 13: Limits and Derivatives',
      'Chapter 14: Mathematical Reasoning',
      'Chapter 15: Statistics',
      'Chapter 16: Probability',
    ],
    'Grade 12': [
      'Chapter 1: Relations and Functions',
      'Chapter 2: Inverse Trigonometric Functions',
      'Chapter 3: Matrices',
      'Chapter 4: Determinants',
      'Chapter 5: Continuity and Differentiability',
      'Chapter 6: Application of Derivatives',
      'Chapter 7: Integrals',
      'Chapter 8: Application of Integrals',
      'Chapter 9: Differential Equations',
      'Chapter 10: Vector Algebra',
      'Chapter 11: Three Dimensional Geometry',
      'Chapter 12: Linear Programming',
      'Chapter 13: Probability',
    ],
  },

  // ── SCIENCE (Grades 6–10) ─────────────────────────────────────────────────────
  Science: {
    'Grade 6': [
      'Chapter 1: Food: Where Does It Come From?',
      'Chapter 2: Components of Food',
      'Chapter 3: Fibre to Fabric',
      'Chapter 4: Sorting Materials into Groups',
      'Chapter 5: Separation of Substances',
      'Chapter 6: Changes Around Us',
      'Chapter 7: Getting to Know Plants',
      'Chapter 8: Body Movements',
      'Chapter 9: The Living Organisms and Their Surroundings',
      'Chapter 10: Motion and Measurement of Distances',
      'Chapter 11: Light, Shadows and Reflections',
      'Chapter 12: Electricity and Circuits',
      'Chapter 13: Fun with Magnets',
      'Chapter 14: Water',
      'Chapter 15: Air Around Us',
      'Chapter 16: Garbage In, Garbage Out',
    ],
    'Grade 7': [
      'Chapter 1: Nutrition in Plants',
      'Chapter 2: Nutrition in Animals',
      'Chapter 3: Fibre to Fabric',
      'Chapter 4: Heat',
      'Chapter 5: Acids, Bases and Salts',
      'Chapter 6: Physical and Chemical Changes',
      'Chapter 7: Weather, Climate and Adaptations of Animals to Climate',
      'Chapter 8: Winds, Storms and Cyclones',
      'Chapter 9: Soil',
      'Chapter 10: Respiration in Organisms',
      'Chapter 11: Transportation in Animals and Plants',
      'Chapter 12: Reproduction in Plants',
      'Chapter 13: Motion and Time',
      'Chapter 14: Electric Current and its Effects',
      'Chapter 15: Light',
      'Chapter 16: Water: A Precious Resource',
      'Chapter 17: Forests: Our Lifeline',
      'Chapter 18: Wastewater Story',
    ],
    'Grade 8': [
      'Chapter 1: Crop Production and Management',
      'Chapter 2: Microorganisms: Friend and Foe',
      'Chapter 3: Synthetic Fibres and Plastics',
      'Chapter 4: Materials: Metals and Non-metals',
      'Chapter 5: Coal and Petroleum',
      'Chapter 6: Combustion and Flame',
      'Chapter 7: Conservation of Plants and Animals',
      'Chapter 8: Cell – Structure and Functions',
      'Chapter 9: Reproduction in Animals',
      'Chapter 10: Reaching the Age of Adolescence',
      'Chapter 11: Force and Pressure',
      'Chapter 12: Friction',
      'Chapter 13: Sound',
      'Chapter 14: Chemical Effects of Electric Current',
      'Chapter 15: Some Natural Phenomena',
      'Chapter 16: Light',
      'Chapter 17: Stars and the Solar System',
      'Chapter 18: Pollution of Air and Water',
    ],
    'Grade 9': [
      'Chapter 1: Matter in Our Surroundings',
      'Chapter 2: Is Matter Around Us Pure?',
      'Chapter 3: Atoms and Molecules',
      'Chapter 4: Structure of the Atom',
      'Chapter 5: The Fundamental Unit of Life',
      'Chapter 6: Tissues',
      'Chapter 7: Diversity in Living Organisms',
      'Chapter 8: Motion',
      'Chapter 9: Force and Laws of Motion',
      'Chapter 10: Gravitation',
      'Chapter 11: Work and Energy',
      'Chapter 12: Sound',
      'Chapter 13: Why Do We Fall Ill?',
      'Chapter 14: Natural Resources',
      'Chapter 15: Improvement in Food Resources',
    ],
    'Grade 10': [
      'Chapter 1: Chemical Reactions and Equations',
      'Chapter 2: Acids, Bases and Salts',
      'Chapter 3: Metals and Non-metals',
      'Chapter 4: Carbon and its Compounds',
      'Chapter 5: Periodic Classification of Elements',
      'Chapter 6: Life Processes',
      'Chapter 7: Control and Coordination',
      'Chapter 8: How do Organisms Reproduce?',
      'Chapter 9: Heredity and Evolution',
      'Chapter 10: Light – Reflection and Refraction',
      'Chapter 11: Human Eye and the Colourful World',
      'Chapter 12: Electricity',
      'Chapter 13: Magnetic Effects of Electric Current',
      'Chapter 14: Sources of Energy',
      'Chapter 15: Our Environment',
      'Chapter 16: Management of Natural Resources',
    ],
  },

  // ── PHYSICS (Grades 11–12) ────────────────────────────────────────────────────
  Physics: {
    'Grade 11': [
      'Chapter 1: Physical World',
      'Chapter 2: Units and Measurement',
      'Chapter 3: Motion in a Straight Line',
      'Chapter 4: Motion in a Plane',
      'Chapter 5: Laws of Motion',
      'Chapter 6: Work, Energy and Power',
      'Chapter 7: System of Particles and Rotational Motion',
      'Chapter 8: Gravitation',
      'Chapter 9: Mechanical Properties of Solids',
      'Chapter 10: Mechanical Properties of Fluids',
      'Chapter 11: Thermal Properties of Matter',
      'Chapter 12: Thermodynamics',
      'Chapter 13: Kinetic Theory',
      'Chapter 14: Oscillations',
      'Chapter 15: Waves',
    ],
    'Grade 12': [
      'Chapter 1: Electric Charges and Fields',
      'Chapter 2: Electrostatic Potential and Capacitance',
      'Chapter 3: Current Electricity',
      'Chapter 4: Moving Charges and Magnetism',
      'Chapter 5: Magnetism and Matter',
      'Chapter 6: Electromagnetic Induction',
      'Chapter 7: Alternating Current',
      'Chapter 8: Electromagnetic Waves',
      'Chapter 9: Ray Optics and Optical Instruments',
      'Chapter 10: Wave Optics',
      'Chapter 11: Dual Nature of Radiation and Matter',
      'Chapter 12: Atoms',
      'Chapter 13: Nuclei',
      'Chapter 14: Semiconductor Electronics: Materials, Devices and Simple Circuits',
      'Chapter 15: Communication Systems',
    ],
  },

  // ── CHEMISTRY (Grades 11–12) ──────────────────────────────────────────────────
  Chemistry: {
    'Grade 11': [
      'Chapter 1: Some Basic Concepts of Chemistry',
      'Chapter 2: Structure of Atom',
      'Chapter 3: Classification of Elements and Periodicity in Properties',
      'Chapter 4: Chemical Bonding and Molecular Structure',
      'Chapter 5: States of Matter',
      'Chapter 6: Thermodynamics',
      'Chapter 7: Equilibrium',
      'Chapter 8: Redox Reactions',
      'Chapter 9: Hydrogen',
      'Chapter 10: The s-Block Element',
      'Chapter 11: The p-Block Elements',
      'Chapter 12: Organic Chemistry – Some Basic Principles and Techniques',
      'Chapter 13: Hydrocarbons',
      'Chapter 14: Environmental Chemistry',
    ],
    'Grade 12': [
      'Chapter 1: The Solid State',
      'Chapter 2: Solutions',
      'Chapter 3: Electrochemistry',
      'Chapter 4: Chemical Kinetics',
      'Chapter 5: Surface Chemistry',
      'Chapter 6: General Principles and Processes of Isolation of Elements',
      'Chapter 7: The p-Block Elements',
      'Chapter 8: The d and f Block Elements',
      'Chapter 9: Coordination Compounds',
      'Chapter 10: Haloalkanes and Haloarenes',
      'Chapter 11: Alcohols, Phenols and Ethers',
      'Chapter 12: Aldehydes, Ketones and Carboxylic Acids',
      'Chapter 13: Amines',
      'Chapter 14: Biomolecules',
      'Chapter 15: Polymers',
      'Chapter 16: Chemistry in Everyday Life',
    ],
  },

  // ── BIOLOGY (Grades 11–12) ────────────────────────────────────────────────────
  Biology: {
    'Grade 11': [
      'Chapter 1: The Living World',
      'Chapter 2: Biological Classification',
      'Chapter 3: Plant Kingdom',
      'Chapter 4: Animal Kingdom',
      'Chapter 5: Morphology of Flowering Plants',
      'Chapter 6: Anatomy of Flowering Plants',
      'Chapter 7: Structural Organisation in Animals',
      'Chapter 8: Cell: The Unit of Life',
      'Chapter 9: Biomolecules',
      'Chapter 10: Cell Cycle and Cell Division',
      'Chapter 11: Transport in Plants',
      'Chapter 12: Mineral Nutrition',
      'Chapter 13: Photosynthesis in Higher Plants',
      'Chapter 14: Respiration in Plants',
      'Chapter 15: Plant Growth and Development',
      'Chapter 16: Digestion and Absorption',
      'Chapter 17: Breathing and Exchange of Gases',
      'Chapter 18: Body Fluids and Circulation',
      'Chapter 19: Excretory Products and their Elimination',
      'Chapter 20: Locomotion and Movement',
      'Chapter 21: Neural Control and Coordination',
      'Chapter 22: Chemical Coordination and Integration',
    ],
    'Grade 12': [
      'Chapter 1: Reproduction in Organisms',
      'Chapter 2: Sexual Reproduction in Flowering Plants',
      'Chapter 3: Human Reproduction',
      'Chapter 4: Reproductive Health',
      'Chapter 5: Principles of Inheritance and Variation',
      'Chapter 6: Molecular Basis of Inheritance',
      'Chapter 7: Evolution',
      'Chapter 8: Human Health and Disease',
      'Chapter 9: Strategies for Enhancement in Food Production',
      'Chapter 10: Microbes in Human Welfare',
      'Chapter 11: Biotechnology: Principles and Processes',
      'Chapter 12: Biotechnology and its Applications',
      'Chapter 13: Organisms and Populations',
      'Chapter 14: Ecosystem',
      'Chapter 15: Biodiversity and Conservation',
      'Chapter 16: Environmental Issues',
    ],
  },

  // ── ENGLISH ───────────────────────────────────────────────────────────────────
  English: {
    'Grade 1':  ['Marigold Book 1 – Unit 1: A Happy Child / Three Little Pigs', 'Unit 2: After a Bath / The Bubble, the Straw and the Shoe', 'Unit 3: One Little Kitten / Lalu and Peelu', 'Unit 4: Once I Saw a Little Bird / Mittu and the Yellow Mango', 'Unit 5: Merry-Go-Round / Circle', 'Unit 6: If I Were an Apple / Our Tree', 'Unit 7: A Kite / Sundari', 'Unit 8: A Little Turtle / The Tiger and the Mosquito', 'Unit 9: Clouds / Anandi\'s Rainbow', 'Unit 10: Flying-Man / The Tailor and his Friend', 'Grammar: Naming Words, Doing Words, Articles, Singular-Plural', 'Writing: Sentence completion, simple sentences, picture-based writing'],
    'Grade 2':  ['Marigold Book 2 – Unit 1: First Day at School / Haldi\'s Adventure', 'Unit 2: I am Lucky / I Want', 'Unit 3: A Smile / The Wind and the Sun', 'Unit 4: Rain / Storm in the Garden', 'Unit 5: Zoo Manners / Funny Bunny', 'Unit 6: Mr. Nobody / Curlylocks and the Three Bears', 'Unit 7: On My Blackboard I Can Draw / Make it Shorter', 'Unit 8: I am the Music Man / The Mumbai Musicians', 'Unit 9: Granny Granny Please Comb My Hair / The Magic Porridge Pot', 'Unit 10: Strange Talk / The Lonely Mountain', 'Grammar: Pronouns, Adjectives, Prepositions', 'Writing: Paragraph writing, picture description'],
    'Grade 3':  ['Marigold Book 3 – Unit 1: Good Morning / The Magic Garden', 'Unit 2: Bird Talk / Nina and the Baby Sparrows', 'Unit 3: Little By Little / The Enormous Turnip', 'Unit 4: Sea Song / A Little Fish Story', 'Unit 5: The Balloon Man / Taro\'s Reward', 'Unit 6: Trains / The Story of the Road', 'Unit 7: Puppy and I / Little Tiger, Big Tiger', 'Unit 8: What\'s in the Mailbox? / My Silly Sister', 'Unit 9: Don\'t Tell / He is My Brother', 'Unit 10: How Creatures Move / The Ship of the Desert', 'Grammar: Tenses (Present, Past), Question Words', 'Writing: Story completion, informal letters'],
    'Grade 4':  ['Marigold Book 4 – Unit 1: Wake Up! / Neha\'s Alarm Clock', 'Unit 2: Noses / The Little Fir Tree', 'Unit 3: Run! / Nasruddin\'s Aim', 'Unit 4: Why / The Giving Tree', 'Unit 5: Don\'t be Afraid of the Dark / Hiawatha', 'Unit 6: Hiawatha / The Scholar\'s Mother', 'Unit 7: A Watering Rhyme / The Donkey', 'Unit 8: Books / Going to Buy a Book', 'Unit 9: Around the World / Pinocchio', 'Unit 10: Transport / The Bus', 'Grammar: Adverbs, Conjunctions, Future Tense', 'Writing: Diary entries, notices, dialogue writing'],
    'Grade 5':  ['Marigold Book 5 – Unit 1: Ice-Cream Man / Wonderful Waste', 'Unit 2: Teamwork / Flying Together', 'Unit 3: My Shadow / Robinson Crusoe', 'Unit 4: Crying / My Elder Brother', 'Unit 5: The Lazy Frog / Rip Van Winkle', 'Unit 6: Class Discussion / The Talkative Barber', 'Unit 7: Topsy-turvy Land / Gulliver\'s Travels', 'Unit 8: Nobody\'s Friend / The Little Bully', 'Unit 9: Sing a Song of People / Around the World', 'Unit 10: Malu Bhalu / Who will be Ningthou?', 'Grammar: Reported Speech, Active-Passive', 'Writing: Formal letter, essay writing'],
    'Grade 6':  ['Honeysuckle – Ch.1: Who Did Patrick\'s Homework?, A House, A Home', 'Ch.2: How the Dog Found Himself a New Master!, The Kite', 'Ch.3: Taro\'s Reward, The Quarrel', 'Ch.4: An Indian – American Woman in Space: Kalpana Chawla, Beauty', 'Ch.5: A Different Kind of School, Where Do All the Teachers Go?', 'Ch.6: Who I Am, The Wonderful Words', 'Ch.7: Fair Play, Vocation', 'Ch.8: A Game of Chance, What If', 'Ch.9: Desert Animals, Camel on the Hill', 'Ch.10: The Banyan Tree, For Anne Gregory', 'A Pact with the Sun (Supplementary Reader): 10 stories', 'Grammar: Nouns, Pronouns, Adjectives, Verbs, Adverbs, Prepositions, Articles, Tenses', 'Writing: Paragraph, Diary, Letter, Notice'],
    'Grade 7':  ['Honeycomb – Ch.1: Three Questions, The Squirrel', 'Ch.2: A Gift of Chappals, The Rebel', 'Ch.3: Gopal and the Hilsa Fish, The Shed', 'Ch.4: The Ashes That Made Trees Bloom, Chivvy', 'Ch.5: Quality, Trees', 'Ch.6: Expert Detectives, Mystery of the Talking Fan', 'Ch.7: The Invention of Vita-Wonk, Dad and the Cat and the Tree', 'Ch.8: Fire: Friend and Foe, Meadow Surprises', 'Ch.9: A Bicycle in Good Repair, Garden Snake', 'Ch.10: The Story of Cricket, The Donkey', 'It So Happened (Supplementary): 10 stories', 'Grammar: Voice, Reported Speech, Modals, Determiners, Word Order', 'Writing: Story, Report, Essay, Bio-sketch'],
    'Grade 8':  ['Honeydew – Ch.1: The Best Christmas Present in the World, The Ant and the Cricket', 'Ch.2: The Tsunami, Geography Lesson', 'Ch.3: Glimpses of the Past, Macavity the Mystery Cat', 'Ch.4: Bepin Choudhury\'s Lapse of Memory, The Last Bargain', 'Ch.5: The Summit Within, The School Boy', 'Ch.6: This is Jody\'s Fawn, The Duck and the Kangaroo', 'Ch.7: A Visit to Cambridge, When I Set Out for Lyonnesse', 'Ch.8: A Short Monsoon Diary, On the Grasshopper and Cricket', 'Ch.9: The Great Stone Face – I & II', 'It So Happened (Supplementary): 10 chapters', 'Grammar: Passive Voice, Clauses, Tense Review, Conditionals', 'Writing: Formal Letter, Article, Speech, Report'],
    'Grade 9':  ['Beehive – Poem 1: The Road Not Taken; Prose 1: The Fun They Had', 'Poem 2: Wind; Prose 2: The Sound of Music', 'Poem 3: Rain on the Roof; Prose 3: The Little Girl', 'Poem 4: The Lake Isle of Innisfree; Prose 4: A Truly Beautiful Mind', 'Poem 5: A Legend of the Northland; Prose 5: The Snake and the Mirror', 'Poem 6: No Men are Foreign; Prose 6: My Childhood', 'Poem 7: The Duck and the Kangaroo; Prose 7: Packing', 'Poem 8: On Killing a Tree; Prose 8: Reach for the Top', 'Poem 9: The Snake Trying; Prose 9: The Bond of Love', 'Poem 10: A Slumber Did My Spirit Seal; Prose 10: Kathmandu', 'Moments (Supplementary): 10 stories', 'Writing Skills: Formal Letter, Story, Descriptive Paragraph, Notice', 'Grammar: Tenses, Modals, Subject-Verb Agreement, Reported Speech, Active-Passive'],
    'Grade 10': ['First Flight – Poem 1: Dust of Snow / Fire and Ice; Prose 1: A Letter to God', 'Poem 2: A Tiger in the Zoo; Prose 2: Nelson Mandela', 'Poem 3: How to Tell Wild Animals; Prose 3: Two Stories about Flying', 'Poem 4: The Ball Poem; Prose 4: From the Diary of Anne Frank', 'Poem 5: Amanda!; Prose 5: The Hundred Dresses (Part 1 & 2)', 'Poem 6: Animals; Prose 6: Glimpses of India', 'Poem 7: The Trees; Prose 7: Mijbil the Otter', 'Poem 8: Fog; Prose 8: Madam Rides the Bus', 'Poem 9: The Tale of Custard the Dragon; Prose 9: The Sermon at Benares', 'Poem 10: For Anne Gregory; Prose 10: The Proposal (Drama)', 'Footprints without Feet (Supplementary): 10 stories', 'Writing Skills: Formal Letter, Analytical Paragraph, Notice, Message', 'Grammar: Tenses, Modals, Active-Passive Voice, Reported Speech, Determiners, Prepositions'],
    'Grade 11': ['Hornbill – Ch.1: The Portrait of a Lady / A Photograph', 'Ch.2: We\'re Not Afraid to Die / The Laburnum Top', 'Ch.3: Discovering Tut / The Voice of the Rain', 'Ch.4: Landscape of the Soul / Childhood', 'Ch.5: The Ailing Planet / Father to Son', 'Ch.6: The Browning Version', 'Ch.7: The Adventure', 'Ch.8: Silk Road', 'Snapshots (Supplementary): The Summer of the Beautiful White Horse, The Address, Ranga\'s Marriage, Albert Einstein at School, Mother\'s Day, The Ghat of the Only World, Birth, The Tale of Melon City', 'Writing Skills: Essay, Notice, Letter, Report, Précis Writing', 'Grammar: Modals, Conditionals, Clauses, Word Formation'],
    'Grade 12': ['Flamingo – Ch.1: The Last Lesson / My Mother at Sixty-six', 'Ch.2: Lost Spring / An Elementary School Classroom in a Slum', 'Ch.3: Deep Water / Keeping Quiet', 'Ch.4: The Rattrap / A Thing of Beauty', 'Ch.5: Indigo / A Roadside Stand', 'Ch.6: Poets and Pancakes / Aunt Jennifer\'s Tigers', 'Ch.7: The Interview / The Road Not Taken (review)', 'Ch.8: Going Places', 'Vistas (Supplementary): The Third Level, The Tiger King, Journey to the End of the Earth, The Enemy, Should Wizard Hit Mommy, On the Face of It, Evans Tries an O-level, Memories of Childhood', 'Writing Skills: Article, Speech, Letter, Report, Advertisement, Notice', 'Grammar: Advanced Grammar Review'],
  },

  // ── HINDI ─────────────────────────────────────────────────────────────────────
  Hindi: {
    'Grade 1':  ['रिमझिम भाग 1 – पाठ 1: झूला', 'पाठ 2: आम की कहानी', 'पाठ 3: आम की टोकरी', 'पाठ 4: पत्ते ही पत्ते', 'पाठ 5: पकौड़ी', 'पाठ 6: छुक-छुक गाड़ी', 'पाठ 7: रसोईघर', 'पाठ 8: चूहो! म्याऊँ सो रही है', 'पाठ 9: बंदर और गिलहरी', 'पाठ 10: पगड़ी', 'पाठ 11: पतंग', 'पाठ 12: गेंद-बल्ला', 'पाठ 13: बंदर गया खेत में भाग', 'पाठ 14: एक बुढ़िया', 'पाठ 15: मैं भी', 'व्याकरण: वर्णमाला, मात्राएँ, शब्द, वाक्य'],
    'Grade 6':  ['वसंत भाग 1 – पाठ 1: वह चिड़िया जो', 'पाठ 2: बचपन', 'पाठ 3: नादान दोस्त', 'पाठ 4: चाँद से थोड़ी सी गप्पें', 'पाठ 5: अक्षरों का महत्व', 'पाठ 6: पार नज़र के', 'पाठ 7: साथी हाथ बढ़ाना', 'पाठ 8: ऐसे – ऐसे', 'पाठ 9: टिकट-अलबम', 'पाठ 10: झांसी की रानी', 'पाठ 11: जो देखकर भी नहीं देखते', 'पाठ 12: संसार पुस्तक है', 'पाठ 13: मैं सबसे छोटी होऊं', 'पाठ 14: लोकगीत', 'पाठ 15: नौकर', 'पाठ 16: वन के मार्ग में', 'पाठ 17: साँस-साँस में बाँस', 'व्याकरण: संज्ञा, सर्वनाम, विशेषण, क्रिया, काल'],
    'Grade 9':  ['क्षितिज भाग 1 – Ch.1: दो बैलों की कथा (Premchand)', 'Ch.2: ल्हासा की ओर (Rahul Sankrityayan)', 'Ch.3: उपभोक्तावाद की संस्कृति', 'Ch.4: साँवले सपनों की याद', 'Ch.5: नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया', 'Ch.6: प्रेमचंद के फटे जूते', 'Ch.7: मेरे बचपन के दिन', 'Ch.8: एक कुत्ता और एक मैना', 'काव्य: कबीर, ललद्यद, रसखान, माखनलाल चतुर्वेदी, सुमित्रानंदन पंत, केदारनाथ अग्रवाल, सर्वेश्वर दयाल सक्सेना', 'कृतिका: 5 chapters', 'व्याकरण: रचना – अपठित, पत्र, निबंध; शब्द-भंडार'],
    'Grade 10': ['क्षितिज भाग 2 – बड़े भाई साहब, डायरी का एक पन्ना, तताँरा-वामीरो कथा, तीसरी कसम के शिल्पकार शैलेंद्र, गिरगिट, अब कहाँ दूसरे के दुख से दुखी होने वाले, पतझर में टूटी पत्तियाँ, कारतूस', 'काव्य: सूरदास, तुलसीदास, देव, जयशंकर प्रसाद, सूर्यकांत त्रिपाठी निराला, नागार्जुन, गिरिजाकुमार माथुर, ऋतुराज, मंगलेश डबराल', 'कृतिका भाग 2: माता का आँचल, जॉर्ज पंचम की नाक, साना साना हाथ जोड़ि, एही ठैयाँ झुलनी हेरानी हो रामा!, मैं क्यों लिखता हूँ?', 'व्याकरण: वाक्य-भेद, समास, अलंकार, छंद, शब्द-भेद, अनेकार्थी शब्द, पत्र, निबंध'],
    'Grade 12': ['आरोह भाग 2 – आत्मपरिचय, एक गीत (Harivanshrai Bachchan), पतंग (Alok Dhanwa), कविता के बहाने, बात सीधी थी पर (Kunwar Narain), कैमरे में बंद अपाहिज (Raghuvir Sahay), सहर्ष स्वीकारा है (Gajanan Madhav Muktibodh), उषा (Shamsher Bahadur Singh), कवितावली / लक्ष्मण-मूर्च्छा (Tulsidas), रुबाइयाँ/गजल (Firaq Gorakhpuri), छोटा मेरा खेत / बगुलों के पंख (Umashankara Joshi)', 'गद्य: भक्तिन, बाज़ार दर्शन, काले मेघा पानी दे, पहलवान की ढोलक, चार्ली चैप्लिन यानी हम सब, नमक, शिरीष के फूल, श्रम-विभाजन और जाति-प्रथा / मेरी कल्पना का आदर्श समाज', 'वितान भाग 2: सिल्वर वैडिंग, जूझ, अतीत में दबे पाँव, डायरी के पन्ने', 'व्याकरण: अपठित, कार्यालयी लेखन, पत्र, निबंध'],
  },

  // ── SOCIAL SCIENCE ────────────────────────────────────────────────────────────
  'Social Science': {
    'Grade 6': [
      'History (Our Pasts I): What, Where, How and When?; On the Trail of the Earliest People; From Gathering to Growing Food; In the Earliest Cities; What Books and Burials Tell Us; Kingdoms, Kings and an Early Republic; New Questions and Ideas; Ashoka, The Emperor Who Gave Up War; Vital Villages, Thriving Towns; Traders, Kings and Pilgrims; New Empires and Kingdoms; Buildings, Paintings and Books',
      'Geography (The Earth: Our Habitat): The Earth in the Solar System; Globe: Latitudes and Longitudes; Motions of the Earth; Maps; Major Domains of the Earth; Major Landforms of the Earth; Our Country – India; India: Climate, Vegetation and Wildlife',
      'Political Science (Social and Political Life I): Understanding Diversity; Diversity and Discrimination; What is Government?; Key Elements of a Democratic Government; Panchayati Raj; Rural Administration; Urban Administration; Rural Livelihoods; Urban Livelihoods',
    ],
    'Grade 7': [
      'History (Our Pasts II): Tracing Changes Through a Thousand Years; New Kings and Kingdoms; The Delhi Sultans; The Mughal Empire; Rulers and Buildings; Towns, Traders and Craftspersons; Tribes, Nomads and Settled Communities; Devotional Paths to the Divine; The Making of Regional Cultures; Eighteenth-Century Political Formations',
      'Geography (Our Environment): Environment; Inside Our Earth; Our Changing Earth; Air; Water; Natural Vegetation and Wildlife; Human Environment – Settlement, Transport and Communication; Human-Environment Interactions; Life in the Temperate Grasslands; Life in the Deserts',
      'Political Science (Social and Political Life II): On Equality; Role of the Government in Health; How the State Government Works; Growing Up as Boys and Girls; Women Change the World; Understanding Media; Markets Around Us; A Shirt in the Market',
    ],
    'Grade 8': [
      'History (Our Pasts III): How, When and Where; From Trade to Territory; Ruling the Countryside; Tribals, Dikus and the Vision of a Golden Age; When People Rebel; Weavers, Iron Smelters and Factory Owners; Civilising the "Native", Educating the Nation; Women, Caste and Reform; The Making of the National Movement: 1870s–1947; India After Independence',
      'Geography (Resources and Development): Resources; Land, Soil, Water, Natural Vegetation and Wildlife Resources; Mineral and Power Resources; Agriculture; Industries; Human Resources',
      'Political Science (Social and Political Life III): The Indian Constitution; Understanding Secularism; Why Do We Need a Parliament?; Understanding Laws; Judiciary; Understanding Our Criminal Justice System; Understanding Marginalisation; Confronting Marginalisation; Public Facilities; Law and Social Justice',
    ],
    'Grade 9': [
      'History (India and the Contemporary World I): The French Revolution; Socialism in Europe and the Russian Revolution; Nazism and the Rise of Hitler; Forest Society and Colonialism; Pastoralists in the Modern World; Peasants and Farmers; History and Sport: The Story of Cricket; Clothing: A Social History',
      'Geography (Contemporary India I): India – Size and Location; Physical Features of India; Drainage; Climate; Natural Vegetation and Wildlife; Population',
      'Political Science (Democratic Politics I): What is Democracy? Why Democracy?; Constitutional Design; Electoral Politics; Working of Institutions; Democratic Rights',
      'Economics (Understanding Economic Development I): The Story of Village Palampur; People as Resource; Poverty as a Challenge; Food Security in India',
    ],
    'Grade 10': [
      'History (India and the Contemporary World II): The Rise of Nationalism in Europe; Nationalism in India; The Making of a Global World; The Age of Industrialisation; Print Culture and the Modern World',
      'Geography (Contemporary India II): Resources and Development; Forest and Wildlife Resources; Water Resources; Agriculture; Minerals and Energy Resources; Manufacturing Industries; Lifelines of National Economy',
      'Political Science (Democratic Politics II): Power Sharing; Federalism; Democracy and Diversity; Gender, Religion and Caste; Popular Struggles and Movements; Political Parties; Outcomes of Democracy; Challenges to Democracy',
      'Economics (Understanding Economic Development II): Development; Sectors of the Indian Economy; Money and Credit; Globalisation and the Indian Economy; Consumer Rights',
    ],
  },

  // ── ENVIRONMENTAL STUDIES (Grades 1–5) ───────────────────────────────────────
  'Environmental Studies (EVS)': {
    'Grade 3': [
      'Chapter 1: Poonam\'s Day Out',
      'Chapter 2: The Plant Fairy',
      'Chapter 3: Water O Water',
      'Chapter 4: Our First School',
      'Chapter 5: Chhotu\'s House',
      'Chapter 6: Foods We Eat',
      'Chapter 7: Saying Without Speaking',
      'Chapter 8: Flying High',
      'Chapter 9: It\'s Raining',
      'Chapter 10: What is Cooking',
      'Chapter 11: From Here to There',
      'Chapter 12: Work We Do',
      'Chapter 13: Sharing Our Feelings',
      'Chapter 14: The Story of Food',
      'Chapter 15: Making Pots',
      'Chapter 16: Games We Play',
      'Chapter 17: Here Comes a Letter',
      'Chapter 18: A House Like This',
      'Chapter 19: Our Friends-Animals',
      'Chapter 20: Drop by Drop',
      'Chapter 21: Families can be Different',
      'Chapter 22: Left Right',
      'Chapter 23: A Beautiful Cloth',
      'Chapter 24: Web of Life',
    ],
    'Grade 4': [
      'Chapter 1: Going to School', 'Chapter 2: Ear to Ear', 'Chapter 3: A Day with Nandu',
      'Chapter 4: The Story of Amrita', 'Chapter 5: Anita and the Honeybees', 'Chapter 6: Omana\'s Journey',
      'Chapter 7: From the Window', 'Chapter 8: Reaching Grandmother\'s House', 'Chapter 9: Changing Families',
      'Chapter 10: Hu Tu Tu, Hu Tu Tu', 'Chapter 11: The Valley of Flowers', 'Chapter 12: Changing Times',
      'Chapter 13: A River\'s Tale', 'Chapter 14: Basva\'s Farm', 'Chapter 15: From Market to Home',
      'Chapter 16: A Busy Month', 'Chapter 17: Nandita in Mumbai', 'Chapter 18: Too Much Water, Too Little Water',
      'Chapter 19: Abdul in the Garden', 'Chapter 20: Eating Together', 'Chapter 21: Food and Fun',
      'Chapter 22: The World in my Home', 'Chapter 23: Pochampalli', 'Chapter 24: Home and Abroad',
      'Chapter 25: Spicy Riddles', 'Chapter 26: Defence Officer: Wahida', 'Chapter 27: Chuskit Goes to School',
    ],
    'Grade 5': [
      'Chapter 1: Super Senses', 'Chapter 2: A Snake Charmer\'s Story', 'Chapter 3: From Tasting to Digesting',
      'Chapter 4: Mangoes Round the Year', 'Chapter 5: Seeds and Seeds', 'Chapter 6: Every Drop Counts',
      'Chapter 7: Experiments with Water', 'Chapter 8: A Treat for Mosquitoes', 'Chapter 9: Up You Go!',
      'Chapter 10: Walls Tell Stories', 'Chapter 11: Sunita in Space', 'Chapter 12: What if it Finishes…?',
      'Chapter 13: A Shelter so High!', 'Chapter 14: When the Earth Shook!', 'Chapter 15: Blow Hot, Blow Cold',
      'Chapter 16: Who Will Do This Work?', 'Chapter 17: Across the Wall', 'Chapter 18: No Place for Us?',
      'Chapter 19: A Seed Tells a Farmer\'s Story', 'Chapter 20: Whose Forests?', 'Chapter 21: Like Father, Like Daughter',
      'Chapter 22: On the Move Again',
    ],
  },

  // ── COMPUTER SCIENCE (Grades 11–12) ──────────────────────────────────────────
  'Computer Science': {
    'Grade 11': [
      'Unit 1: Computer Fundamentals – Computer system organisation, memory concepts, input/output devices',
      'Unit 2: Programming Methodology – Problem solving, algorithms, flowcharts, program structure',
      'Unit 3: Python Basics – Introduction to Python, data types, operators, expressions, I/O',
      'Unit 4: Control Flow – if/elif/else, for loop, while loop, break, continue',
      'Unit 5: Functions – Defining functions, parameters, return values, scope, recursion',
      'Unit 6: Strings – String operations, built-in methods, string slicing',
      'Unit 7: Lists – List operations, methods, list comprehension, nested lists',
      'Unit 8: Tuples and Dictionaries – Tuple operations, dictionary operations, methods',
      'Unit 9: File Handling – Text files, binary files, CSV files, reading and writing',
      'Unit 10: Societal Impacts – Digital footprint, cybercrime, plagiarism, intellectual property, e-waste',
    ],
    'Grade 12': [
      'Unit 1: Review of Python – Advanced functions, decorators, generators',
      'Unit 2: Exception Handling – try/except/finally, custom exceptions',
      'Unit 3: File Handling (Advanced) – Random access, CSV, binary files',
      'Unit 4: Object-Oriented Programming – Classes, objects, inheritance, polymorphism, encapsulation',
      'Unit 5: Recursion – Recursive functions, base case, Tower of Hanoi',
      'Unit 6: Data Structures – Stack, Queue, Linked List using Python',
      'Unit 7: Database Management – RDBMS concepts, SQL: DDL, DML, DCL, joins, grouping',
      'Unit 8: MySQL with Python – Connecting Python to MySQL, executing queries',
      'Unit 9: Networking – Types of networks, protocols, topology, HTML basics, web technologies',
      'Unit 10: Cyber Security – Threats, firewalls, encryption, safe practices, societal impacts',
    ],
  },
};

// ─── ICSE Official Chapter Mapping ───────────────────────────────────────────

export const ICSE_CHAPTERS: Record<string, Record<string, string[]>> = {
  Mathematics: {
    'Grade 9': [
      'Chapter 1: Rational and Irrational Numbers', 'Chapter 2: Compound Interest',
      'Chapter 3: Expansions', 'Chapter 4: Factorisation', 'Chapter 5: Simultaneous Linear Equations',
      'Chapter 6: Indices/Exponents', 'Chapter 7: Logarithms', 'Chapter 8: Triangles',
      'Chapter 9: Mid-Point and Intercept Theorems', 'Chapter 10: Rectilinear Figures',
      'Chapter 11: Construction of Polygons', 'Chapter 12: Pythagoras Theorem',
      'Chapter 13: Rectilinear Figures (Area)', 'Chapter 14: Circle',
      'Chapter 15: Statistics', 'Chapter 16: Mensuration', 'Chapter 17: Trigonometry',
      'Chapter 18: Co-ordinate Geometry',
    ],
    'Grade 10': [
      'Chapter 1: GST (Goods and Services Tax)', 'Chapter 2: Banking',
      'Chapter 3: Shares and Dividends', 'Chapter 4: Linear Inequations',
      'Chapter 5: Quadratic Equations', 'Chapter 6: Solving Simple Problems (Algebra)',
      'Chapter 7: Ratio and Proportion', 'Chapter 8: Remainder and Factor Theorems',
      'Chapter 9: Matrices', 'Chapter 10: Arithmetic Progression',
      'Chapter 11: Geometric Progression', 'Chapter 12: Reflection',
      'Chapter 13: Section and Mid-Point Formulae', 'Chapter 14: Equation of a Line',
      'Chapter 15: Similarity', 'Chapter 16: Loci (Locus and Its Constructions)',
      'Chapter 17: Circles', 'Chapter 18: Tangents and Intersecting Chords',
      'Chapter 19: Constructions (Circles)', 'Chapter 20: Cylinder, Cone and Sphere (Surface Area and Volume)',
      'Chapter 21: Trigonometrical Identities', 'Chapter 22: Height and Distances',
      'Chapter 23: Graphical Representation (Histograms)', 'Chapter 24: Measures of Central Tendency (Mean, Median, Quartiles and Mode)',
      'Chapter 25: Probability',
    ],
  },
  Physics: {
    'Grade 9': [
      'Chapter 1: Measurements and Experimentation', 'Chapter 2: Motion in One Dimension',
      'Chapter 3: Laws of Motion', 'Chapter 4: Pressure in Fluids and Atmospheric Pressure',
      'Chapter 5: Upthrust in Fluids, Archimedes\' Principle and Floatation',
      'Chapter 6: Heat and Energy', 'Chapter 7: Reflection of Light',
      'Chapter 8: Propagation of Sound Waves', 'Chapter 9: Current Electricity',
      'Chapter 10: Magnetism',
    ],
    'Grade 10': [
      'Chapter 1: Force', 'Chapter 2: Work, Energy and Power',
      'Chapter 3: Machines', 'Chapter 4: Refraction of Light at Plane Surfaces',
      'Chapter 5: Refraction through a Lens', 'Chapter 6: Spectrum',
      'Chapter 7: Sound', 'Chapter 8: Electricity',
      'Chapter 9: Electrical Power and Household Circuits', 'Chapter 10: Electromagnetism',
      'Chapter 11: Calorimetry', 'Chapter 12: Radioactivity',
    ],
  },
  Chemistry: {
    'Grade 9': [
      'Chapter 1: The Language of Chemistry', 'Chapter 2: Chemical Changes and Reactions',
      'Chapter 3: Water', 'Chapter 4: Atomic Structure and Chemical Bonding',
      'Chapter 5: The Periodic Table', 'Chapter 6: Study of the First Element: Hydrogen',
      'Chapter 7: Study of Gas Laws', 'Chapter 8: Atmospheric Pollution',
    ],
    'Grade 10': [
      'Chapter 1: Periodic Properties and Variations of Properties', 'Chapter 2: Chemical Bonding',
      'Chapter 3: Study of Acids, Bases and Salts', 'Chapter 4: Analytical Chemistry',
      'Chapter 5: Mole Concept and Stoichiometry', 'Chapter 6: Electrolysis',
      'Chapter 7: Metallurgy', 'Chapter 8: Study of Compounds: Hydrogen Chloride',
      'Chapter 9: Study of Compounds: Ammonia', 'Chapter 10: Study of Compounds: Nitric Acid',
      'Chapter 11: Study of Compounds: Sulphuric Acid', 'Chapter 12: Organic Chemistry',
    ],
  },
  Biology: {
    'Grade 9': [
      'Chapter 1: Introduction to Biology', 'Chapter 2: Cell: The Unit of Life',
      'Chapter 3: Tissues: Plant and Animal', 'Chapter 4: The Flower',
      'Chapter 5: Pollination and Fertilisation', 'Chapter 6: Seeds: Structure and Germination',
      'Chapter 7: Respiration in Plants', 'Chapter 8: Five Kingdom Classification',
      'Chapter 9: Economic Importance of Bacteria and Fungi', 'Chapter 10: Nutrition',
      'Chapter 11: Digestive System', 'Chapter 12: Skeleton – Movement and Locomotion',
    ],
    'Grade 10': [
      'Chapter 1: Cell Cycle, Cell Division and Structure of Chromosomes',
      'Chapter 2: Genetics: Mendel\'s Laws and Inheritance', 'Chapter 3: Absorption by Roots',
      'Chapter 4: Transpiration', 'Chapter 5: Photosynthesis', 'Chapter 6: Chemical Coordination in Plants',
      'Chapter 7: The Circulatory System', 'Chapter 8: The Excretory System',
      'Chapter 9: The Nervous System and Sense Organs', 'Chapter 10: The Endocrine System',
      'Chapter 11: The Reproductive System', 'Chapter 12: Human Evolution',
      'Chapter 13: Pollution', 'Chapter 14: Human Genome Project and Genetic Engineering',
    ],
  },
};

// ─── Helper: Get board-specific chapter context for AI prompt ─────────────────

export function getBoardChapterContext(board: string, grade: string, subject: string): string {
  const normBoard = board.toUpperCase().replace(/[^A-Z]/g, '');
  const normSubject = subject.trim();

  // CBSE chapter lookup
  if (normBoard === 'CBSE' || normBoard.includes('CBSE')) {
    const chapters = CBSE_CHAPTERS[normSubject]?.[grade];
    if (chapters && chapters.length > 0) {
      return `OFFICIAL NCERT/CBSE CHAPTERS for ${subject} ${grade}:\n${chapters.map((c, i) => `  ${i + 1}. ${c}`).join('\n')}\n\nYou MUST generate curriculum units that cover ALL these official chapters in the correct sequence. Do NOT invent or substitute chapter names.`;
    }
  }

  // ICSE chapter lookup
  if (normBoard === 'ICSE' || normBoard === 'ISC' || normBoard.includes('ICSE')) {
    const chapters = ICSE_CHAPTERS[normSubject]?.[grade];
    if (chapters && chapters.length > 0) {
      return `OFFICIAL ICSE CHAPTERS for ${subject} ${grade}:\n${chapters.map((c, i) => `  ${i + 1}. ${c}`).join('\n')}\n\nYou MUST generate curriculum units that cover ALL these official chapters in the correct sequence.`;
    }
  }

  // IB guidance
  if (normBoard === 'IB') {
    const gradeNum = parseInt(grade.replace(/\D/g, ''));
    if (gradeNum <= 5) return `This is IB PYP (Primary Years Programme). Design curriculum around 6 transdisciplinary themes: Who We Are, Where We Are in Place and Time, How We Express Ourselves, How the World Works, How We Organize Ourselves, Sharing the Planet. Central Ideas must drive all units.`;
    if (gradeNum <= 10) return `This is IB MYP (Middle Years Programme). Structure units around: Key Concept, Related Concepts, Global Context, Statement of Inquiry, Inquiry Questions, ATL Skills, Summative Assessment Task (criteria A/B/C/D).`;
    return `This is IB DP (Diploma Programme). Align to official IB ${subject} syllabus with internal assessment, external assessment, core content, and optional themes as prescribed.`;
  }

  // Cambridge guidance
  if (normBoard === 'CAMBRIDGE' || normBoard === 'CAIE') {
    return `This is Cambridge ${grade} ${subject}. Follow the Cambridge Learning Objectives framework with strands, sub-strands, and learning objectives. Reference the Cambridge Learner Guide and Scheme of Work.`;
  }

  // Generic fallback
  return `Generate curriculum for ${board} ${grade} ${subject} following standard pedagogical frameworks, Bloom's Taxonomy, and spiral curriculum principles. Use authentic chapter/topic names as prescribed by the ${board} syllabus.`;
}

// ─── Subject validation: check if a subject is valid for a grade/board ────────

export function getValidSubjectsForGrade(board: string, grade: string): string[] {
  const normBoard = Object.keys(BOARD_GRADE_SUBJECTS).find(
    b => b.toLowerCase() === board.toLowerCase()
  ) || 'CBSE';
  return BOARD_GRADE_SUBJECTS[normBoard]?.[grade] || [];
}
